### ISSUE TITLE
Only superviser should be able to cancel APPROVED vacations

### ISSUE THREAD

**Issue by santee** [SoftwareCountry/arcadian-assistant#303] opened 2018-11-29 13:22 UTC
Do not allow to cancel own APPROVED vacations (relevant for calendar screen). For profile screen, supervisor should be able to cancel it.

**Comment by antonm76** [comment] 2018-11-30 08:59
Doesn't it look like a duplicate of #300?

**Comment by sponkrashin** [comment] 2018-11-30 11:14
That issue is about server side, and this one is about mobile side.

**Comment by antonm76** [comment] 2018-12-03 09:39
Right!

**Comment by sponkrashin** [comment] 2018-12-05 12:11
From related issue #300: added new permission CancelApprovedCalendarEvents.

**Comment by antonm76** [comment] 2018-12-12 14:43
Done. a08602272409c49cfc30d4407e10d5be4c2ad111

**Comment by KuchaLeni** [comment] 2019-01-31 15:02
Verified.

**Closed by KuchaLeni** 2019-01-31 15:02 UTC
Labels: mobile
